# Generated by Django 5.1.4 on 2025-01-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('long_url', models.URLField(max_length=10000)),
                ('short_url', models.URLField(max_length=1000)),
            ],
        ),
    ]
