# Generated by Django 5.1.4 on 2025-01-20 07:51

import django.db.models.deletion
import url.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_url_created_at_url_expires_at_alter_url_long_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='url.url'),
        ),
        migrations.AlterField(
            model_name='url',
            name='expires_at',
            field=models.DateTimeField(default=url.models.default_expiry),
        ),
        migrations.AlterField(
            model_name='url',
            name='long_url',
            field=models.URLField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
