# Generated by Django 5.1.4 on 2025-01-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_url_access_count_alter_accesslog_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
